server:
    host: localhost
    port: 2211
database:
  user: arno
  password: 909209866sh
  dbname: TODO
  host: localhost
  port: 5432
  ssl_mode: disable
token:
  secret: Arno
  access_exp: 60s
  refresh_exp: 120s