database:
  user: arno
  password: 5O4QjCtgfT0W71p4ugmtwb1WbwjMS2Ds
  dbname: todo_px3l
  host: dpg-cubld0ogph6c73a7dls0-a
  port: 5432
  ssl_mode: disable
token:
  secret: Arno
  access_exp: 60s
  refresh_exp: 120s